server:
  port: 8081

spring:
  datasource:

    url: jdbc:postgresql://dpg-d8ml14rbc2fs73e3t420-a.singapore-postgres.render.com:5432/hrms_6dhs?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: hrms
    password: "m2dSZ1DuhFHZsnqw4rhemsw7ZdjoaIsy"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG

app:
  jwt:
    secret: hrms-demo-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm-ok
    expiration: 86400000   # 24 hours
