server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/hr_system
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "051126"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG

app:
  jwt:
    secret: hrms-demo-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm-ok
    expiration: 86400000   # 24 hours
